Blog App: validations and model specs
kalbek/blog-app pull request #5
Opened 2023-07-21 13:38 UTC by kalbek

2023-07-21 14:40 UTC, fobadara requested changes
Hi @kalbek, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Good first attempt
✅ Good file structure

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because it could not be done inline
[REQUIRED]  I tried running your tests but I get errors when I use the commands you mentioned in your README.  Kindly fix this and tell us how to run your test properly in your README.
<img width="1440" alt="image" src="https://github.com/kalbek/blog-app/assets/62938735/83c3e6f3-b170-493b-bafb-353658cec2c3">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 14:40 UTC, fobadara commented on test/models/post_test.rb
[OPTIONAL] Using a description block make it easier for other developers to understand your tests. I think you should do something like this:
```
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```

2023-07-21 14:40 UTC, fobadara commented on test/models/user_test.rb
[OPTIONAL] Using a description block make it easier for other developers to understand your tests. I think you should do something like this:
```
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```

2023-07-21 14:40 UTC, fobadara commented on README.md
[REQUIRED] In your README file in the `key features` you have a long dash that is doing nothing. This makes your project look unprofessional. Kindly fix this:
<img width="1440" alt="image" src="https://github.com/kalbek/blog-app/assets/62938735/99208364-1908-463c-90c1-83ce063f088c">

2023-07-22 08:28 UTC, AmaduKamara approved these changes
# Status: Approved 🟢 🟢 🟢

Hi @kalbek, 

Good job working on the changes highlighted by the previous reviewer 👍🏽

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Set validation and model specs 👍🏽
✅ All tests passed successfully 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-07-22 08:32 UTC, merged